### ISSUE TITLE
'onChange' not getting triggered after version 1.12.4 update

### ISSUE THREAD

**Issue by RVenkatesh** [adopted-ember-addons/ember-sortable#234]
We had been using the sortable for few months. After the 1.12.4 update, the 'onChange' event is not getting triggered. I am testing using Chrome 71.0.3578.98 (Official Build) (64-bit). Below is the code sample.

```
{{#sortable-group onChange=(action "reorderOptions") as |group|}}
	{{#each (sort-by "sortorder" options) as |option|}}
		{{#sortable-item model=option group=group class="option" handle=".sort-handle"}}
			{{#if (and canEdit (gt options.length 1))}}
				<i class="fa fa-bars sort-handle"></i>
			{{/if}}
			{{option-comp}}
		{{/sortable-item}}
	{{/each}}
{{/sortable-group}} 
```

And the component js file has the action
```
reorderOptions(options, movedOption) {
     // Commit to model code
}
```

I have not added the full code for the action, since the action itself is not getting called anyway. I did some digging and looks like the `commit` function itself is not getting called inside the addon. 

Any help would be great. Thank you in advance.

**Comment by dhinesh03** [comment]
I too have this issue.

**Comment by jgwhite** [comment]
Thanks for reporting. It seems like the changes we introduced to fix some Firefox issues have caused regressions elsewhere. Will report back when we have a plan to move ahead. As a temporary measure, we recommend pinning to 1.12.3.

**Comment by BnitoBzh** [comment]
YES !!! I found a (the?) solution !!! 🎉 
All `.sortable-item` MUST have a css property with a transition like `transition: all .125s;`
Because, if not, the event `transistionend` is not fired in Firefox. (due to the `_waitForTransition` function refactor on the "sortable-item" Mixin that adds this behavior)

Sass/CSS example to fix the issue : 
```css
// in scss or sass file
.sortable-item {
  transition: all .125s;
  
  &.is-dragging {
    transition-duration: 0s;
  }
}

// or in css file
.sortable-item {
  transition: all .125s;
}
.sortable-item.is-dragging {
  transition-duration: 0s;
}
```
